# Generated by Django 5.1.3 on 2024-12-11 02:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_doors_alter_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
