# Generated by Django 5.1.3 on 2024-12-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_description_alter_car_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='interioR',
            new_name='interior',
        ),
    ]
